### ISSUE TITLE
Marking components as validated/confirmed/curated

### ISSUE THREAD

**Issue by willbar** [amzn/oss-attribution-builder#13]
We've been considering the ability to mark license/copyright information as having been validated/confirmed/curated if an "approved" person has looked at it (or the information has come from a trusted source).

I'm considering a couple of changes and wanted to get your input on them:
- Add an attribute to components to flag that the information has been validated (probably a date and some kind of field to track who did the validation)
- Add a page that lists components and allows them to be edited (specifically to allow marking a component as validated)
- In the component selector when you're editing a product's attribution provide some kind of indicator against validated components

**Comment by jpeddicord** [comment]
To clarify, are you talking about additional functionality on top of "verified packages" (see [here](https://github.com/amzn/oss-attribution-builder/blob/master/docs/for-admins.md#verifying-packages))? Your first and second pieces are implemented in some fashion, but they could be made more accessible. The third item would be relatively easy to implement: the verified data is present in the response, but not rendered in the component search box/selector.

**Comment by willbar** [comment]
I hadn't seen that! I think that does everything we need.

**Comment by jpeddicord** [comment]
Hah. I'll take that as feedback that the feature needs to be more visible. :D
