### ISSUE TITLE
Programmatic access

### ISSUE THREAD

**Issue by jpeddicord** [amzn/oss-attribution-builder#20]
Right now, the attribution builder assumes that a person is using the website. This is reflected in audit logs, access checks, etc. It's possible to implement a custom auth backend that allows for programmatic access, but that gets a little hacky and doesn't play nice with traditional authentication.

To solve issues like #14, I'm thinking of building in support for programmatic clients that access the site via API keys. These keys will map to user accounts and will be stored in a new database table (or perhaps Redis, since it's in the firing line of a request). These could then be configured to access resources via the usual configuration system. API clients could then present an Authorization header with said key.

I'd imagine the format of that table would look something like this:

username | api key | roles
--- | --- | ---
bot-account-1 | oaridgmcfpuydarxst | [ add-packages, verify-packages ]

I'm not sure there will be any kind of UI for this; at most there'd be a CLI tool to create an API service user. Still thinking of specifics, but there's a rough overview.

**Comment by jamesiri** [comment]
#44
