### ISSUE TITLE
Issues with large projects

### ISSUE THREAD

**Issue by jpeddicord** [amzn/oss-attribution-builder#24]
On bigger projects, oss-a-b can be a bit slow since the JSON payload for `packages_used` is sync'd for each edit. This can result in a sluggish UI and apparent timeouts, resulting in duplicated packages submitted. Then, when removing a duplicate, both packages get removed since they'd have the same package ID. (This doesn't affect multiple revisions of packages, since those would result in new IDs for modifications.)

**Comment by jamesiri** [comment]
#44
