### ISSUE TITLE
API: creating a new project returns "You cannot remove yourself as an owner."

### ISSUE THREAD

**Issue by julscha** [amzn/oss-attribution-builder#31]
There is another Issue I ran into. When I first used the API to create a new Project, I would use an input structure as follows: 
`data class NewProject(
        val title: String,
        val version: String,
        val description: String,
        val plannedRelease: String,
        val contacts: Contacts,
        val acl: ACL,
        val metadata: ObjectNode
    )` 

`data class ACL(
        val everyone: String
    )`

This would work perfectly fine, as long as `val everyone = "owner"`
Now, going through the code again, I changed it to:
`enum class ACL(private val permission: String) {
        OWNER("owner"),
        EDITOR("editor"),
        VIEWER("viewer");
        @JsonValue
        override fun toString() = permission
    }`
And the same request returns: "error":"You cannot remove yourself as an owner." for `ACL.OWNER`

I can't really see, where/ why/ how that happens :(
Weirdly, the same error occurs when I change it back to the first implementation, but replace the value name by anything else but "everyone". For example:

`data class ACL(
        val role: String
    )`

Could *anyone* ;) clarify this for me?

**Comment by jpeddicord** [comment]
The error you're seeing comes from some validation logic that attempts to ensure that a project isn't left in an unusable state. This error message is general, but also affects new projects (it could be better). Basically, it's telling you that with the permissions you've specified, the project you've created has permissions that prevent you from editing it.

How to fix this is going to depend on the authorization backend you're using. The only one we ship in this project is [nullauth](https://github.com/amzn/oss-attribution-builder/blob/master/server/auth/impl/nullauth.ts), which is set up as a demonstration. This has a couple properties: 1) you're in a group called `self:yourusername`, and 2) everyone is in a group called `everyone` (you can see that at the bottom of the file linked).

If you wanted to replicate that (before implementing authorization), you'd want to set a key of `self:username` to `owner`, replacing the `username` with whatever user you're supplying for authentication. But you'll want to replace that authorization backend with something more geared for production use. :)

At Amazon we have a custom back-end set up to work with our internal SSO and LDAP systems. i.e., `getGroups` will query our directory for groups that the viewing user is a member of. Here's a small snippet of that:

```
  async getGroups(user: string): Promise<string[]> {
    const ldapGroups = await this._ldapsearch('ou=groups,o=.....', {
      scope: 'sub',
      filter: 'memberuid=' + encodeURIComponent(user),
      attributes: ['cn'],
    }, (obj) => `ldap:${obj.cn}`);
...
    return ldapGroups;
  }
```

Bit more to it than just that, but that's the general idea. The groups you supply in the ACL structure (when creating or modifying a project) have to have at least _one_ with a value of `owner` and a key that is the output of `getGroups`. In other words, the key has to be one of the current user's groups.

Does that help answer your question?

**Comment by sschuberth** [comment]
Chiming in here, when looking at

https://github.com/amzn/oss-attribution-builder/blob/5548c3e21d3f2c6eaccb79c971689904e5cee5c4/docs/openapi.yaml#L230-L231

and

https://github.com/amzn/oss-attribution-builder/blob/5548c3e21d3f2c6eaccb79c971689904e5cee5c4/docs/openapi.yaml#L89-L96

I also found it hard to understand that ACL is not actually a single string / enum, but a (hash)map (I guess that's what JavaScript generically calls an "object") of (authentication backend specific) strings to permissions, where permissions can be one of "owner", "editor" or "viewer". Correct?

**Comment by jpeddicord** [comment]
Correct. It's a map/object where the keys are group names (from `getGroups`), and values are one of `owner`, `editor`, and `viewer`.

**Comment by jamesiri** [comment]
#44
