### ISSUE TITLE
TAGS: transformCopyright() not working as expected with 'notice'

### ISSUE THREAD

**Issue by cursor42** [amzn/oss-attribution-builder#33]
The function `transformCopyright()` may be provided by TAGS attached to a license to modify the text to be produced for the copyright statement.

For `Apache-2.0` license the tag `notice` is defined which should strip off the copyright notice at the beginning of the attribution text and append it as 'see following NOTICE:' at the end.

This does not seem to work as expected, as the following steps show:

* Create a new project
* Define a new package using 'Apache-2.0' license.
*  Build attribution document.

The document generated contains the copyright notice TWICE, one occurence at the beginning of the text and one at the end.

The expected behavior is that the copyright NOTICE only appears ONCE at the end of the text.

**Comment by jpeddicord** [comment]
Confirmed.  This probably regressed when we switched logic to use tiny-attribution-generator. Likely a simple fix; will investigate.

**Comment by cursor42** [comment]
Thanks! It seems that `transformCopyright()` is not called at all. I did some tests returning some dummy text - which could not be found in the final document.

**Comment by jpeddicord** [comment]
Messing with this today. It does appear to be getting called (I stuck a console.log in notice.ts to check) but the result doesn't seem to be correctly used. Digging.

**Comment by cursor42** [comment]
NOTICE now works as expected, thank you very much for the fix!
